name: Humble Binary Build
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - test_error

jobs:
  binary:
    uses: fmauch/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@debug_ici_outputs
    strategy:
      matrix:
        ROS_DISTRO: [humble]
        ROS_REPO: [main, testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: ros2_control-not-released.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: humble
